name: tagmaps
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=18.2.0
  - descartes=1.1.0
  - fiona=1.8.4
  - gdal=2.4.0
  - geos=3.7.1
  - hdbscan=0.8.19
  - matplotlib=3.0.2
  - mkl
  - numpy=1.15.4
  - pandas=0.24.1
  - proj4=5.2.0
  - python=3.6.6
  - scikit-learn>=0.20.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - shapely=1.6.4
  - regex=2019.02.07
  - bitarray
  - pyproj
  - cython
  - pip:
    - attr==0.3.1
    - emoji==0.5.1
    - pylint
    - anybadge
    - pylint-exit

