site_name: Tag Maps Documentation
site_url: https://ad.gitlab.vgiscience.de/tagmaps/docs
site_author: Alexander Dunkel
copyright: © Copyright 2019, Alexander Dunkel
site_dir: site

repo_url: https://github.com/Sieboldianus/TagMaps/

theme:
  name: 'readthedocs'

markdown_extensions:
  - admonition
  
nav:
    - Introduction: index.md
    - Contents: contents.md
    - Quick Installation: quick-guide.md
    - Concept: theory/introduction.md
    - User Guide:
        - Detailed installation guide: user-guide/installation.md
        - Use your own data: user-guide/use-your-own-data.md
        - Tutorial: user-guide/tutorial.md
        - Jupyter lab examples: user-guide/jupyter-examples.md
        - Troubleshooting: user-guide/troubleshooting.md
    - Command Line Args and Usage: argparse/args.md
    - API Reference (external): api/tagmaps_.html
    - Additional resources: resources.md
    - About: about.md
