{% set name = "tagmaps" %}
{% set version = "0.17.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4613bd37f82444b1bb6cdf810eeb7367529ae65305984963ee58dfa1ee965092

build:
  noarch: python
  number: 0
  skip: True  # [py<35]
  entry_points:
    - tagmaps = tagmaps.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python 3.6.*
    - pip
    - shapely>=1.6.4
    - fiona>=1.8.6
    - pandas>=0.24.2
    - pyproj>=1.9.6
    - numpy>=1.15.4
    - matplotlib>=3.0.3
    - emoji>=0.5.1
    - cython>=0.29.7
    - hdbscan>=0.8.20
    - gdal>=2.4.0
    - attrs>=19.1.0
    - seaborn>=0.9.0
    - descartes>=1.1.0
    - regex>=2019.04.14
    - scipy>=1.2.1
  run:
    - python 3.6.*
    - shapely>=1.6.4
    - fiona>=1.8.6
    - pandas>=0.24.2
    - pyproj>=1.9.6
    - numpy>=1.15.4
    - matplotlib>=3.0.3
    - emoji>=0.5.1
    - cython>=0.29.7
    - hdbscan>=0.8.20
    - gdal>=2.4.0
    - attrs>=19.1.0
    - seaborn>=0.9.0
    - descartes>=1.1.0
    - regex>=2019.04.14
    - scipy>=1.2.1

test:
  imports:
    - tagmaps
  commands:
    - tagmaps --help

about:
  home: https://github.com/Sieboldianus/TagMaps
  license: GNU GPLv3 or any higher
  license_family: GPL3
  license_file: 
  summary: Tag Clustering for Tag Maps
  description: |
    Perform tag clustering from spatially referenced and tagged records.
    TagMaps performs itemized or global clustering based on a list of records with
    multiple tags (or emoji) attached. Utilizes HDBSCAN for determining cluster
    results at specific (optional user defined) distance. Tags, Locations and
    Emoji are processed in descending order of global occurence, alpha
    shapes are generated for cluster point clouds. Produces two output
    shapefiles with cluster shapes that can be visualized, e.g. in ESRI ArcGIS.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - Sieboldianus
